### ISSUE TITLE
Add Rust to Python bindings

### ISSUE THREAD

**Issue by Korbad** [profpoochie/rust_practice#2]
Add a button which:
1. executes a Python module using the Rust->Python bindings
2. displays the result

The goal is to eventually interface with the ansible-runner Python interface:
https://ansible-runner.readthedocs.io/en/stable/python_interface/

**Comment by profpoochie** [comment]
Rust app the runs a python script [here](https://github.com/profpoochie/rust_practice/blob/main/rust_python/src/main.rs)
